### PR TITLE
fixed up example and removed reference to nonexisting cloud example.

### PR DESCRIPTION
**Pull request by gilescope**
Cloud example wasn't compiling but an easy fixup. Some of those examples are very inspiring!
Thank you for putting this together.

### CODE REVIEW

**Comment by eliotbo** [comment]
Thank you!
Would you be interested in contributing your 3d version?

**Comment by gilescope** [comment]
Not sure what you mean? Would love to see these in wasm but trunk has no way to launch examples at the moment.

**Comment by eliotbo** [comment]
Ahh! I've mistaken you for somebody else. Sorry.

I'd really like to have wasm compatibility too, but the code needs a major change for it to be the case. I believe webgl2 does not recognize compute shaders, so I would need to use fragment shaders instead.

**Comment by gilescope** [comment]
I hear that they might work with webgpu enabled (behind browser flags at
the moment) … or at least the compute shaders of bevy_atmosphere will
allegedly.

**Pull request merged**
